// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: spire/hostservice/server/identityprovider/v1/identityprovider.proto

package identityproviderv1

import (
	types "github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchX509IdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchX509IdentityRequest) Reset() {
	*x = FetchX509IdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchX509IdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509IdentityRequest) ProtoMessage() {}

func (x *FetchX509IdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509IdentityRequest.ProtoReflect.Descriptor instead.
func (*FetchX509IdentityRequest) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescGZIP(), []int{0}
}

type FetchX509IdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The X.509 identity.
	Identity *X509Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Required. The bundle of the trust domain.
	Bundle *types.Bundle `protobuf:"bytes,2,opt,name=bundle,proto3" json:"bundle,omitempty"`
}

func (x *FetchX509IdentityResponse) Reset() {
	*x = FetchX509IdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchX509IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchX509IdentityResponse) ProtoMessage() {}

func (x *FetchX509IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchX509IdentityResponse.ProtoReflect.Descriptor instead.
func (*FetchX509IdentityResponse) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescGZIP(), []int{1}
}

func (x *FetchX509IdentityResponse) GetIdentity() *X509Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *FetchX509IdentityResponse) GetBundle() *types.Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type X509Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The certificate chain (ASN.1 encoded). The first certificate
	// in the chain is the leaf (e.g. the X509-SVID).
	CertChain [][]byte `protobuf:"bytes,1,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	// Required. The private key for the identity (PKCS #8 encoded).
	PrivateKey []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
}

func (x *X509Identity) Reset() {
	*x = X509Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509Identity) ProtoMessage() {}

func (x *X509Identity) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509Identity.ProtoReflect.Descriptor instead.
func (*X509Identity) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescGZIP(), []int{2}
}

func (x *X509Identity) GetCertChain() [][]byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

func (x *X509Identity) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

var File_spire_hostservice_server_identityprovider_v1_identityprovider_proto protoreflect.FileDescriptor

var file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDesc = []byte{
	0x0a, 0x43, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2c, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x68, 0x6f, 0x73,
	0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x58, 0x35, 0x30,
	0x39, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xa7, 0x01, 0x0a, 0x19, 0x46, 0x65, 0x74, 0x63, 0x68, 0x58, 0x35, 0x30, 0x39, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3a, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x58, 0x35, 0x30, 0x39, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x52, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x4e, 0x0a, 0x0c, 0x58, 0x35,
	0x30, 0x39, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x65,
	0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09,
	0x63, 0x65, 0x72, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x32, 0xb9, 0x01, 0x0a, 0x10, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12,
	0xa4, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x58, 0x35, 0x30, 0x39, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x46, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x68, 0x6f,
	0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x58, 0x35, 0x30, 0x39, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x47, 0x2e,
	0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x58, 0x35, 0x30, 0x39, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6a, 0x5a, 0x68, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x69, 0x66, 0x66, 0x65, 0x2f, 0x73, 0x70, 0x69, 0x72,
	0x65, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescOnce sync.Once
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescData = file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDesc
)

func file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescGZIP() []byte {
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescOnce.Do(func() {
		file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescData = protoimpl.X.CompressGZIP(file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescData)
	})
	return file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDescData
}

var file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_goTypes = []interface{}{
	(*FetchX509IdentityRequest)(nil),  // 0: spire.hostservice.server.identityprovider.v1.FetchX509IdentityRequest
	(*FetchX509IdentityResponse)(nil), // 1: spire.hostservice.server.identityprovider.v1.FetchX509IdentityResponse
	(*X509Identity)(nil),              // 2: spire.hostservice.server.identityprovider.v1.X509Identity
	(*types.Bundle)(nil),              // 3: spire.plugin.types.Bundle
}
var file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_depIdxs = []int32{
	2, // 0: spire.hostservice.server.identityprovider.v1.FetchX509IdentityResponse.identity:type_name -> spire.hostservice.server.identityprovider.v1.X509Identity
	3, // 1: spire.hostservice.server.identityprovider.v1.FetchX509IdentityResponse.bundle:type_name -> spire.plugin.types.Bundle
	0, // 2: spire.hostservice.server.identityprovider.v1.IdentityProvider.FetchX509Identity:input_type -> spire.hostservice.server.identityprovider.v1.FetchX509IdentityRequest
	1, // 3: spire.hostservice.server.identityprovider.v1.IdentityProvider.FetchX509Identity:output_type -> spire.hostservice.server.identityprovider.v1.FetchX509IdentityResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_init() }
func file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_init() {
	if File_spire_hostservice_server_identityprovider_v1_identityprovider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchX509IdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchX509IdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*X509Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_goTypes,
		DependencyIndexes: file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_depIdxs,
		MessageInfos:      file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_msgTypes,
	}.Build()
	File_spire_hostservice_server_identityprovider_v1_identityprovider_proto = out.File
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_rawDesc = nil
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_goTypes = nil
	file_spire_hostservice_server_identityprovider_v1_identityprovider_proto_depIdxs = nil
}
