// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: spire/plugin/server/bundlepublisher/v1/bundlepublisher.proto

package bundlepublisherv1

import (
	types "github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishBundleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. The trust bundle to publish.
	Bundle *types.Bundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
}

func (x *PublishBundleRequest) Reset() {
	*x = PublishBundleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleRequest) ProtoMessage() {}

func (x *PublishBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleRequest.ProtoReflect.Descriptor instead.
func (*PublishBundleRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP(), []int{0}
}

func (x *PublishBundleRequest) GetBundle() *types.Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type PublishBundleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishBundleResponse) Reset() {
	*x = PublishBundleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleResponse) ProtoMessage() {}

func (x *PublishBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleResponse.ProtoReflect.Descriptor instead.
func (*PublishBundleResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP(), []int{1}
}

var File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto protoreflect.FileDescriptor

var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc = []byte{
	0x0a, 0x3c, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26,
	0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x62, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x32, 0x0a, 0x06, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x06, 0x62, 0x75, 0x6e,
	0x64, 0x6c, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa0, 0x01, 0x0a,
	0x0f, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72,
	0x12, 0x8c, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x12, 0x3c, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x3d, 0x2e, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x63, 0x5a, 0x61, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70,
	0x69, 0x66, 0x66, 0x65, 0x2f, 0x73, 0x70, 0x69, 0x72, 0x65, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x69, 0x72,
	0x65, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2f,
	0x76, 0x31, 0x3b, 0x62, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescOnce sync.Once
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData = file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc
)

func file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP() []byte {
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescOnce.Do(func() {
		file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData = protoimpl.X.CompressGZIP(file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData)
	})
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData
}

var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes = []interface{}{
	(*PublishBundleRequest)(nil),  // 0: spire.plugin.server.bundlepublisher.v1.PublishBundleRequest
	(*PublishBundleResponse)(nil), // 1: spire.plugin.server.bundlepublisher.v1.PublishBundleResponse
	(*types.Bundle)(nil),          // 2: spire.plugin.types.Bundle
}
var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs = []int32{
	2, // 0: spire.plugin.server.bundlepublisher.v1.PublishBundleRequest.bundle:type_name -> spire.plugin.types.Bundle
	0, // 1: spire.plugin.server.bundlepublisher.v1.BundlePublisher.PublishBundle:input_type -> spire.plugin.server.bundlepublisher.v1.PublishBundleRequest
	1, // 2: spire.plugin.server.bundlepublisher.v1.BundlePublisher.PublishBundle:output_type -> spire.plugin.server.bundlepublisher.v1.PublishBundleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_init() }
func file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_init() {
	if File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishBundleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishBundleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes,
		DependencyIndexes: file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs,
		MessageInfos:      file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes,
	}.Build()
	File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto = out.File
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc = nil
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes = nil
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs = nil
}
