// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/plugin/server/bundlepublisher/v1/bundlepublisher.proto

package bundlepublisherv1

import (
	types "github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishBundleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The trust bundle to publish.
	Bundle        *types.Bundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBundleRequest) Reset() {
	*x = PublishBundleRequest{}
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleRequest) ProtoMessage() {}

func (x *PublishBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleRequest.ProtoReflect.Descriptor instead.
func (*PublishBundleRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP(), []int{0}
}

func (x *PublishBundleRequest) GetBundle() *types.Bundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

type PublishBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBundleResponse) Reset() {
	*x = PublishBundleResponse{}
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBundleResponse) ProtoMessage() {}

func (x *PublishBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBundleResponse.ProtoReflect.Descriptor instead.
func (*PublishBundleResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP(), []int{1}
}

var File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto protoreflect.FileDescriptor

const file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc = "" +
	"\n" +
	"<spire/plugin/server/bundlepublisher/v1/bundlepublisher.proto\x12&spire.plugin.server.bundlepublisher.v1\x1a\x1fspire/plugin/types/bundle.proto\"J\n" +
	"\x14PublishBundleRequest\x122\n" +
	"\x06bundle\x18\x01 \x01(\v2\x1a.spire.plugin.types.BundleR\x06bundle\"\x17\n" +
	"\x15PublishBundleResponse2\xa0\x01\n" +
	"\x0fBundlePublisher\x12\x8c\x01\n" +
	"\rPublishBundle\x12<.spire.plugin.server.bundlepublisher.v1.PublishBundleRequest\x1a=.spire.plugin.server.bundlepublisher.v1.PublishBundleResponseBcZagithub.com/spiffe/spire-plugin-sdk/proto/spire/plugin/server/bundlepublisher/v1;bundlepublisherv1b\x06proto3"

var (
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescOnce sync.Once
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData []byte
)

func file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescGZIP() []byte {
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescOnce.Do(func() {
		file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc), len(file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc)))
	})
	return file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDescData
}

var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes = []any{
	(*PublishBundleRequest)(nil),  // 0: spire.plugin.server.bundlepublisher.v1.PublishBundleRequest
	(*PublishBundleResponse)(nil), // 1: spire.plugin.server.bundlepublisher.v1.PublishBundleResponse
	(*types.Bundle)(nil),          // 2: spire.plugin.types.Bundle
}
var file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs = []int32{
	2, // 0: spire.plugin.server.bundlepublisher.v1.PublishBundleRequest.bundle:type_name -> spire.plugin.types.Bundle
	0, // 1: spire.plugin.server.bundlepublisher.v1.BundlePublisher.PublishBundle:input_type -> spire.plugin.server.bundlepublisher.v1.PublishBundleRequest
	1, // 2: spire.plugin.server.bundlepublisher.v1.BundlePublisher.PublishBundle:output_type -> spire.plugin.server.bundlepublisher.v1.PublishBundleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_init() }
func file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_init() {
	if File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc), len(file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes,
		DependencyIndexes: file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs,
		MessageInfos:      file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_msgTypes,
	}.Build()
	File_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto = out.File
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_goTypes = nil
	file_spire_plugin_server_bundlepublisher_v1_bundlepublisher_proto_depIdxs = nil
}
