// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SomeServiceClient is the client API for SomeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SomeServiceClient interface {
	ServiceEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type someServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSomeServiceClient(cc grpc.ClientConnInterface) SomeServiceClient {
	return &someServiceClient{cc}
}

func (c *someServiceClient) ServiceEcho(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/test.SomeService/ServiceEcho", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SomeServiceServer is the server API for SomeService service.
// All implementations must embed UnimplementedSomeServiceServer
// for forward compatibility
type SomeServiceServer interface {
	ServiceEcho(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedSomeServiceServer()
}

// UnimplementedSomeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSomeServiceServer struct {
}

func (UnimplementedSomeServiceServer) ServiceEcho(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceEcho not implemented")
}
func (UnimplementedSomeServiceServer) mustEmbedUnimplementedSomeServiceServer() {}

// UnsafeSomeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SomeServiceServer will
// result in compilation errors.
type UnsafeSomeServiceServer interface {
	mustEmbedUnimplementedSomeServiceServer()
}

func RegisterSomeServiceServer(s grpc.ServiceRegistrar, srv SomeServiceServer) {
	s.RegisterService(&SomeService_ServiceDesc, srv)
}

func _SomeService_ServiceEcho_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SomeServiceServer).ServiceEcho(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.SomeService/ServiceEcho",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SomeServiceServer).ServiceEcho(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SomeService_ServiceDesc is the grpc.ServiceDesc for SomeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SomeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.SomeService",
	HandlerType: (*SomeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceEcho",
			Handler:    _SomeService_ServiceEcho_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/someservice.proto",
}
