// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/plugin/types/bundle.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bundle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the trust domain the bundle belongs to (e.g., "example.org").
	TrustDomain string `protobuf:"bytes,1,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	// X.509 authorities for authenticating X509-SVIDs.
	X509Authorities []*X509Certificate `protobuf:"bytes,2,rep,name=x509_authorities,json=x509Authorities,proto3" json:"x509_authorities,omitempty"`
	// JWT authorities for authenticating JWT-SVIDs.
	JwtAuthorities []*JWTKey `protobuf:"bytes,3,rep,name=jwt_authorities,json=jwtAuthorities,proto3" json:"jwt_authorities,omitempty"`
	// A hint on how often the bundle should be refreshed from the bundle
	// provider, in seconds. Can be zero (meaning no hint available).
	RefreshHint int64 `protobuf:"varint,4,opt,name=refresh_hint,json=refreshHint,proto3" json:"refresh_hint,omitempty"`
	// The sequence number of the bundle.
	SequenceNumber uint64 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	mi := &file_spire_plugin_types_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_types_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_spire_plugin_types_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *Bundle) GetTrustDomain() string {
	if x != nil {
		return x.TrustDomain
	}
	return ""
}

func (x *Bundle) GetX509Authorities() []*X509Certificate {
	if x != nil {
		return x.X509Authorities
	}
	return nil
}

func (x *Bundle) GetJwtAuthorities() []*JWTKey {
	if x != nil {
		return x.JwtAuthorities
	}
	return nil
}

func (x *Bundle) GetRefreshHint() int64 {
	if x != nil {
		return x.RefreshHint
	}
	return 0
}

func (x *Bundle) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

var File_spire_plugin_types_bundle_proto protoreflect.FileDescriptor

const file_spire_plugin_types_bundle_proto_rawDesc = "" +
	"\n" +
	"\x1fspire/plugin/types/bundle.proto\x12\x12spire.plugin.types\x1a\x1fspire/plugin/types/jwtkey.proto\x1a(spire/plugin/types/x509certificate.proto\"\x8c\x02\n" +
	"\x06Bundle\x12!\n" +
	"\ftrust_domain\x18\x01 \x01(\tR\vtrustDomain\x12N\n" +
	"\x10x509_authorities\x18\x02 \x03(\v2#.spire.plugin.types.X509CertificateR\x0fx509Authorities\x12C\n" +
	"\x0fjwt_authorities\x18\x03 \x03(\v2\x1a.spire.plugin.types.JWTKeyR\x0ejwtAuthorities\x12!\n" +
	"\frefresh_hint\x18\x04 \x01(\x03R\vrefreshHint\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x04R\x0esequenceNumberB=Z;github.com/spiffe/spire-plugin-sdk/proto/spire/plugin/typesb\x06proto3"

var (
	file_spire_plugin_types_bundle_proto_rawDescOnce sync.Once
	file_spire_plugin_types_bundle_proto_rawDescData []byte
)

func file_spire_plugin_types_bundle_proto_rawDescGZIP() []byte {
	file_spire_plugin_types_bundle_proto_rawDescOnce.Do(func() {
		file_spire_plugin_types_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_plugin_types_bundle_proto_rawDesc), len(file_spire_plugin_types_bundle_proto_rawDesc)))
	})
	return file_spire_plugin_types_bundle_proto_rawDescData
}

var file_spire_plugin_types_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spire_plugin_types_bundle_proto_goTypes = []any{
	(*Bundle)(nil),          // 0: spire.plugin.types.Bundle
	(*X509Certificate)(nil), // 1: spire.plugin.types.X509Certificate
	(*JWTKey)(nil),          // 2: spire.plugin.types.JWTKey
}
var file_spire_plugin_types_bundle_proto_depIdxs = []int32{
	1, // 0: spire.plugin.types.Bundle.x509_authorities:type_name -> spire.plugin.types.X509Certificate
	2, // 1: spire.plugin.types.Bundle.jwt_authorities:type_name -> spire.plugin.types.JWTKey
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_plugin_types_bundle_proto_init() }
func file_spire_plugin_types_bundle_proto_init() {
	if File_spire_plugin_types_bundle_proto != nil {
		return
	}
	file_spire_plugin_types_jwtkey_proto_init()
	file_spire_plugin_types_x509certificate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_plugin_types_bundle_proto_rawDesc), len(file_spire_plugin_types_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_plugin_types_bundle_proto_goTypes,
		DependencyIndexes: file_spire_plugin_types_bundle_proto_depIdxs,
		MessageInfos:      file_spire_plugin_types_bundle_proto_msgTypes,
	}.Build()
	File_spire_plugin_types_bundle_proto = out.File
	file_spire_plugin_types_bundle_proto_goTypes = nil
	file_spire_plugin_types_bundle_proto_depIdxs = nil
}
