// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/plugin/agent/workloadattestor/v2/workloadattestor.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestReferenceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Reference to the workload to be attested.
	Reference     *anypb.Any `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestReferenceRequest) Reset() {
	*x = AttestReferenceRequest{}
	mi := &file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestReferenceRequest) ProtoMessage() {}

func (x *AttestReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestReferenceRequest.ProtoReflect.Descriptor instead.
func (*AttestReferenceRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescGZIP(), []int{0}
}

func (x *AttestReferenceRequest) GetReference() *anypb.Any {
	if x != nil {
		return x.Reference
	}
	return nil
}

type AttestReferenceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Selector values related to the attested workload. The type
	// of the selector is inferred from the plugin name.
	SelectorValues []string `protobuf:"bytes,1,rep,name=selector_values,json=selectorValues,proto3" json:"selector_values,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttestReferenceResponse) Reset() {
	*x = AttestReferenceResponse{}
	mi := &file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestReferenceResponse) ProtoMessage() {}

func (x *AttestReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestReferenceResponse.ProtoReflect.Descriptor instead.
func (*AttestReferenceResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescGZIP(), []int{1}
}

func (x *AttestReferenceResponse) GetSelectorValues() []string {
	if x != nil {
		return x.SelectorValues
	}
	return nil
}

var File_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto protoreflect.FileDescriptor

const file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDesc = "" +
	"\n" +
	"=spire/plugin/agent/workloadattestor/v2/workloadattestor.proto\x12&spire.plugin.agent.workloadattestor.v2\x1a\x19google/protobuf/any.proto\"L\n" +
	"\x16AttestReferenceRequest\x122\n" +
	"\treference\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\treference\"B\n" +
	"\x17AttestReferenceResponse\x12'\n" +
	"\x0fselector_values\x18\x01 \x03(\tR\x0eselectorValues2\xa7\x01\n" +
	"\x10WorkloadAttestor\x12\x92\x01\n" +
	"\x0fAttestReference\x12>.spire.plugin.agent.workloadattestor.v2.AttestReferenceRequest\x1a?.spire.plugin.agent.workloadattestor.v2.AttestReferenceResponseBQZOgithub.com/spiffe/spire-plugin-sdk/proto/spire/plugin/agent/workloadattestor/v2b\x06proto3"

var (
	file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescOnce sync.Once
	file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescData []byte
)

func file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescGZIP() []byte {
	file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescOnce.Do(func() {
		file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDesc), len(file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDesc)))
	})
	return file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDescData
}

var file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_goTypes = []any{
	(*AttestReferenceRequest)(nil),  // 0: spire.plugin.agent.workloadattestor.v2.AttestReferenceRequest
	(*AttestReferenceResponse)(nil), // 1: spire.plugin.agent.workloadattestor.v2.AttestReferenceResponse
	(*anypb.Any)(nil),               // 2: google.protobuf.Any
}
var file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_depIdxs = []int32{
	2, // 0: spire.plugin.agent.workloadattestor.v2.AttestReferenceRequest.reference:type_name -> google.protobuf.Any
	0, // 1: spire.plugin.agent.workloadattestor.v2.WorkloadAttestor.AttestReference:input_type -> spire.plugin.agent.workloadattestor.v2.AttestReferenceRequest
	1, // 2: spire.plugin.agent.workloadattestor.v2.WorkloadAttestor.AttestReference:output_type -> spire.plugin.agent.workloadattestor.v2.AttestReferenceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_init() }
func file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_init() {
	if File_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDesc), len(file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_goTypes,
		DependencyIndexes: file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_depIdxs,
		MessageInfos:      file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_msgTypes,
	}.Build()
	File_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto = out.File
	file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_goTypes = nil
	file_spire_plugin_agent_workloadattestor_v2_workloadattestor_proto_depIdxs = nil
}
