// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: spire/plugin/agent/workloadattestor/v2/workloadattestor.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadAttestor_AttestReference_FullMethodName = "/spire.plugin.agent.workloadattestor.v2.WorkloadAttestor/AttestReference"
)

// WorkloadAttestorClient is the client API for WorkloadAttestor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkloadAttestorClient interface {
	AttestReference(ctx context.Context, in *AttestReferenceRequest, opts ...grpc.CallOption) (*AttestReferenceResponse, error)
}

type workloadAttestorClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadAttestorClient(cc grpc.ClientConnInterface) WorkloadAttestorClient {
	return &workloadAttestorClient{cc}
}

func (c *workloadAttestorClient) AttestReference(ctx context.Context, in *AttestReferenceRequest, opts ...grpc.CallOption) (*AttestReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestReferenceResponse)
	err := c.cc.Invoke(ctx, WorkloadAttestor_AttestReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadAttestorServer is the server API for WorkloadAttestor service.
// All implementations must embed UnimplementedWorkloadAttestorServer
// for forward compatibility.
type WorkloadAttestorServer interface {
	AttestReference(context.Context, *AttestReferenceRequest) (*AttestReferenceResponse, error)
	mustEmbedUnimplementedWorkloadAttestorServer()
}

// UnimplementedWorkloadAttestorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadAttestorServer struct{}

func (UnimplementedWorkloadAttestorServer) AttestReference(context.Context, *AttestReferenceRequest) (*AttestReferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestReference not implemented")
}
func (UnimplementedWorkloadAttestorServer) mustEmbedUnimplementedWorkloadAttestorServer() {}
func (UnimplementedWorkloadAttestorServer) testEmbeddedByValue()                          {}

// UnsafeWorkloadAttestorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadAttestorServer will
// result in compilation errors.
type UnsafeWorkloadAttestorServer interface {
	mustEmbedUnimplementedWorkloadAttestorServer()
}

func RegisterWorkloadAttestorServer(s grpc.ServiceRegistrar, srv WorkloadAttestorServer) {
	// If the following call pancis, it indicates UnimplementedWorkloadAttestorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadAttestor_ServiceDesc, srv)
}

func _WorkloadAttestor_AttestReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadAttestorServer).AttestReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadAttestor_AttestReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadAttestorServer).AttestReference(ctx, req.(*AttestReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkloadAttestor_ServiceDesc is the grpc.ServiceDesc for WorkloadAttestor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadAttestor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spire.plugin.agent.workloadattestor.v2.WorkloadAttestor",
	HandlerType: (*WorkloadAttestorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttestReference",
			Handler:    _WorkloadAttestor_AttestReference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spire/plugin/agent/workloadattestor/v2/workloadattestor.proto",
}
