// Code generated by protoc-gen-go-spire. DO NOT EDIT.

package sviserverattestorv1

import (
	pluginsdk "github.com/spiffe/spire-plugin-sdk/pluginsdk"
	grpc "google.golang.org/grpc"
)

func ServerAttestorPluginServer(server ServerAttestorServer) pluginsdk.PluginServer {
	return serverAttestorPluginServer{ServerAttestorServer: server}
}

type serverAttestorPluginServer struct {
	ServerAttestorServer
}

func (s serverAttestorPluginServer) Type() string {
	return "ServerAttestor"
}

func (s serverAttestorPluginServer) GRPCServiceName() string {
	return "spire.plugin.agent.serverattestor.v1.ServerAttestor"
}

func (s serverAttestorPluginServer) RegisterServer(server *grpc.Server) interface{} {
	RegisterServerAttestorServer(server, s.ServerAttestorServer)
	return s.ServerAttestorServer
}

type ServerAttestorPluginClient struct {
	ServerAttestorClient
}

func (s ServerAttestorPluginClient) Type() string {
	return "ServerAttestor"
}

func (c *ServerAttestorPluginClient) IsInitialized() bool {
	return c.ServerAttestorClient != nil
}

func (c *ServerAttestorPluginClient) GRPCServiceName() string {
	return "spire.plugin.agent.serverattestor.v1.ServerAttestor"
}

func (c *ServerAttestorPluginClient) InitClient(conn grpc.ClientConnInterface) interface{} {
	c.ServerAttestorClient = NewServerAttestorClient(conn)
	return c.ServerAttestorClient
}
