// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: spire/plugin/server/upstreamauthority/v1/upstreamauthority.proto

package upstreamauthorityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpstreamAuthority_MintX509CAAndSubscribe_FullMethodName    = "/spire.plugin.server.upstreamauthority.v1.UpstreamAuthority/MintX509CAAndSubscribe"
	UpstreamAuthority_PublishJWTKeyAndSubscribe_FullMethodName = "/spire.plugin.server.upstreamauthority.v1.UpstreamAuthority/PublishJWTKeyAndSubscribe"
	UpstreamAuthority_SubscribeToLocalBundle_FullMethodName    = "/spire.plugin.server.upstreamauthority.v1.UpstreamAuthority/SubscribeToLocalBundle"
)

// UpstreamAuthorityClient is the client API for UpstreamAuthority service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpstreamAuthorityClient interface {
	// Mints an X.509 CA and responds with the signed X.509 CA certificate
	// chain and upstream X.509 roots. If supported by the implementation,
	// subsequent responses on the stream contain upstream X.509 root updates,
	// otherwise the stream is closed after the initial response.
	//
	// Implementation note:
	// The stream should be kept open in the face of transient errors
	// encountered while tracking changes to the upstream X.509 roots as SPIRE
	// Server will not reopen a closed stream until the next X.509 CA rotation.
	MintX509CAAndSubscribe(ctx context.Context, in *MintX509CARequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MintX509CAResponse], error)
	// Publishes a JWT signing key upstream and responds with the upstream JWT
	// keys. If supported by the implementation, subsequent responses on the
	// stream contain upstream JWT key updates, otherwise the stream is closed
	// after the initial response.
	//
	// This RPC is optional and will return NotImplemented if unsupported.
	//
	// Implementation note:
	// The stream should be kept open in the face of transient errors
	// encountered while tracking changes to the upstream JWT keys as SPIRE
	// Server will not reopen a closed stream until the next JWT key rotation.
	PublishJWTKeyAndSubscribe(ctx context.Context, in *PublishJWTKeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PublishJWTKeyResponse], error)
	// Returns the trust bundle of the local trust domain as seen by the upstream
	// authority. Returns the current set of X.509 roots and JWT public keys
	// that make up the trust bundle of the trust domain. If supported by the
	// implementation, subsequent responses on the stream contain trust bundle
	// updates, otherwise the stream is closed after the initial response.
	//
	// This RPC is optional and will return NotImplemented if unsupported.
	SubscribeToLocalBundle(ctx context.Context, in *SubscribeToLocalBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeToLocalBundleResponse], error)
}

type upstreamAuthorityClient struct {
	cc grpc.ClientConnInterface
}

func NewUpstreamAuthorityClient(cc grpc.ClientConnInterface) UpstreamAuthorityClient {
	return &upstreamAuthorityClient{cc}
}

func (c *upstreamAuthorityClient) MintX509CAAndSubscribe(ctx context.Context, in *MintX509CARequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MintX509CAResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpstreamAuthority_ServiceDesc.Streams[0], UpstreamAuthority_MintX509CAAndSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MintX509CARequest, MintX509CAResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_MintX509CAAndSubscribeClient = grpc.ServerStreamingClient[MintX509CAResponse]

func (c *upstreamAuthorityClient) PublishJWTKeyAndSubscribe(ctx context.Context, in *PublishJWTKeyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PublishJWTKeyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpstreamAuthority_ServiceDesc.Streams[1], UpstreamAuthority_PublishJWTKeyAndSubscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishJWTKeyRequest, PublishJWTKeyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_PublishJWTKeyAndSubscribeClient = grpc.ServerStreamingClient[PublishJWTKeyResponse]

func (c *upstreamAuthorityClient) SubscribeToLocalBundle(ctx context.Context, in *SubscribeToLocalBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeToLocalBundleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UpstreamAuthority_ServiceDesc.Streams[2], UpstreamAuthority_SubscribeToLocalBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToLocalBundleRequest, SubscribeToLocalBundleResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_SubscribeToLocalBundleClient = grpc.ServerStreamingClient[SubscribeToLocalBundleResponse]

// UpstreamAuthorityServer is the server API for UpstreamAuthority service.
// All implementations must embed UnimplementedUpstreamAuthorityServer
// for forward compatibility.
type UpstreamAuthorityServer interface {
	// Mints an X.509 CA and responds with the signed X.509 CA certificate
	// chain and upstream X.509 roots. If supported by the implementation,
	// subsequent responses on the stream contain upstream X.509 root updates,
	// otherwise the stream is closed after the initial response.
	//
	// Implementation note:
	// The stream should be kept open in the face of transient errors
	// encountered while tracking changes to the upstream X.509 roots as SPIRE
	// Server will not reopen a closed stream until the next X.509 CA rotation.
	MintX509CAAndSubscribe(*MintX509CARequest, grpc.ServerStreamingServer[MintX509CAResponse]) error
	// Publishes a JWT signing key upstream and responds with the upstream JWT
	// keys. If supported by the implementation, subsequent responses on the
	// stream contain upstream JWT key updates, otherwise the stream is closed
	// after the initial response.
	//
	// This RPC is optional and will return NotImplemented if unsupported.
	//
	// Implementation note:
	// The stream should be kept open in the face of transient errors
	// encountered while tracking changes to the upstream JWT keys as SPIRE
	// Server will not reopen a closed stream until the next JWT key rotation.
	PublishJWTKeyAndSubscribe(*PublishJWTKeyRequest, grpc.ServerStreamingServer[PublishJWTKeyResponse]) error
	// Returns the trust bundle of the local trust domain as seen by the upstream
	// authority. Returns the current set of X.509 roots and JWT public keys
	// that make up the trust bundle of the trust domain. If supported by the
	// implementation, subsequent responses on the stream contain trust bundle
	// updates, otherwise the stream is closed after the initial response.
	//
	// This RPC is optional and will return NotImplemented if unsupported.
	SubscribeToLocalBundle(*SubscribeToLocalBundleRequest, grpc.ServerStreamingServer[SubscribeToLocalBundleResponse]) error
	mustEmbedUnimplementedUpstreamAuthorityServer()
}

// UnimplementedUpstreamAuthorityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpstreamAuthorityServer struct{}

func (UnimplementedUpstreamAuthorityServer) MintX509CAAndSubscribe(*MintX509CARequest, grpc.ServerStreamingServer[MintX509CAResponse]) error {
	return status.Errorf(codes.Unimplemented, "method MintX509CAAndSubscribe not implemented")
}
func (UnimplementedUpstreamAuthorityServer) PublishJWTKeyAndSubscribe(*PublishJWTKeyRequest, grpc.ServerStreamingServer[PublishJWTKeyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PublishJWTKeyAndSubscribe not implemented")
}
func (UnimplementedUpstreamAuthorityServer) SubscribeToLocalBundle(*SubscribeToLocalBundleRequest, grpc.ServerStreamingServer[SubscribeToLocalBundleResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToLocalBundle not implemented")
}
func (UnimplementedUpstreamAuthorityServer) mustEmbedUnimplementedUpstreamAuthorityServer() {}
func (UnimplementedUpstreamAuthorityServer) testEmbeddedByValue()                           {}

// UnsafeUpstreamAuthorityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpstreamAuthorityServer will
// result in compilation errors.
type UnsafeUpstreamAuthorityServer interface {
	mustEmbedUnimplementedUpstreamAuthorityServer()
}

func RegisterUpstreamAuthorityServer(s grpc.ServiceRegistrar, srv UpstreamAuthorityServer) {
	// If the following call pancis, it indicates UnimplementedUpstreamAuthorityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpstreamAuthority_ServiceDesc, srv)
}

func _UpstreamAuthority_MintX509CAAndSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MintX509CARequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpstreamAuthorityServer).MintX509CAAndSubscribe(m, &grpc.GenericServerStream[MintX509CARequest, MintX509CAResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_MintX509CAAndSubscribeServer = grpc.ServerStreamingServer[MintX509CAResponse]

func _UpstreamAuthority_PublishJWTKeyAndSubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PublishJWTKeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpstreamAuthorityServer).PublishJWTKeyAndSubscribe(m, &grpc.GenericServerStream[PublishJWTKeyRequest, PublishJWTKeyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_PublishJWTKeyAndSubscribeServer = grpc.ServerStreamingServer[PublishJWTKeyResponse]

func _UpstreamAuthority_SubscribeToLocalBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToLocalBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpstreamAuthorityServer).SubscribeToLocalBundle(m, &grpc.GenericServerStream[SubscribeToLocalBundleRequest, SubscribeToLocalBundleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UpstreamAuthority_SubscribeToLocalBundleServer = grpc.ServerStreamingServer[SubscribeToLocalBundleResponse]

// UpstreamAuthority_ServiceDesc is the grpc.ServiceDesc for UpstreamAuthority service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpstreamAuthority_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spire.plugin.server.upstreamauthority.v1.UpstreamAuthority",
	HandlerType: (*UpstreamAuthorityServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MintX509CAAndSubscribe",
			Handler:       _UpstreamAuthority_MintX509CAAndSubscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PublishJWTKeyAndSubscribe",
			Handler:       _UpstreamAuthority_PublishJWTKeyAndSubscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToLocalBundle",
			Handler:       _UpstreamAuthority_SubscribeToLocalBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "spire/plugin/server/upstreamauthority/v1/upstreamauthority.proto",
}
