// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/service/private/init/v1/init.proto

package initv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Init request parameters
type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all the names of gRPC services implemented by the host (i.e.
	// SPIRE). These names are the fully qualified gRPC service name (e.g.
	// spire.hostservice.v1.Foo).
	HostServiceNames []string `protobuf:"bytes,1,rep,name=host_service_names,json=hostServiceNames,proto3" json:"host_service_names,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_spire_service_private_init_v1_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetHostServiceNames() []string {
	if x != nil {
		return x.HostServiceNames
	}
	return nil
}

// Init response parameters
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of all the names of gRPC services implemented by the service. These
	// names are the fully qualified gRPC service name (e.g.
	// spire.plugin.server.keymanager.v1.Keymanager).
	PluginServiceNames []string `protobuf:"bytes,1,rep,name=plugin_service_names,json=pluginServiceNames,proto3" json:"plugin_service_names,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_spire_service_private_init_v1_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetPluginServiceNames() []string {
	if x != nil {
		return x.PluginServiceNames
	}
	return nil
}

// Deinit request parameters
type DeinitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitRequest) Reset() {
	*x = DeinitRequest{}
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitRequest) ProtoMessage() {}

func (x *DeinitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitRequest.ProtoReflect.Descriptor instead.
func (*DeinitRequest) Descriptor() ([]byte, []int) {
	return file_spire_service_private_init_v1_init_proto_rawDescGZIP(), []int{2}
}

// Deinit response parameters
type DeinitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitResponse) Reset() {
	*x = DeinitResponse{}
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitResponse) ProtoMessage() {}

func (x *DeinitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_service_private_init_v1_init_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitResponse.ProtoReflect.Descriptor instead.
func (*DeinitResponse) Descriptor() ([]byte, []int) {
	return file_spire_service_private_init_v1_init_proto_rawDescGZIP(), []int{3}
}

var File_spire_service_private_init_v1_init_proto protoreflect.FileDescriptor

const file_spire_service_private_init_v1_init_proto_rawDesc = "" +
	"\n" +
	"(spire/service/private/init/v1/init.proto\x12\x1dspire.service.private.init.v1\";\n" +
	"\vInitRequest\x12,\n" +
	"\x12host_service_names\x18\x01 \x03(\tR\x10hostServiceNames\"@\n" +
	"\fInitResponse\x120\n" +
	"\x14plugin_service_names\x18\x01 \x03(\tR\x12pluginServiceNames\"\x0f\n" +
	"\rDeinitRequest\"\x10\n" +
	"\x0eDeinitResponse2\xce\x01\n" +
	"\x04Init\x12_\n" +
	"\x04Init\x12*.spire.service.private.init.v1.InitRequest\x1a+.spire.service.private.init.v1.InitResponse\x12e\n" +
	"\x06Deinit\x12,.spire.service.private.init.v1.DeinitRequest\x1a-.spire.service.private.init.v1.DeinitResponseBXZVgithub.com/spiffe/spire-plugin-sdk/internal/proto/spire/service/private/init/v1;initv1b\x06proto3"

var (
	file_spire_service_private_init_v1_init_proto_rawDescOnce sync.Once
	file_spire_service_private_init_v1_init_proto_rawDescData []byte
)

func file_spire_service_private_init_v1_init_proto_rawDescGZIP() []byte {
	file_spire_service_private_init_v1_init_proto_rawDescOnce.Do(func() {
		file_spire_service_private_init_v1_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_service_private_init_v1_init_proto_rawDesc), len(file_spire_service_private_init_v1_init_proto_rawDesc)))
	})
	return file_spire_service_private_init_v1_init_proto_rawDescData
}

var file_spire_service_private_init_v1_init_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_spire_service_private_init_v1_init_proto_goTypes = []any{
	(*InitRequest)(nil),    // 0: spire.service.private.init.v1.InitRequest
	(*InitResponse)(nil),   // 1: spire.service.private.init.v1.InitResponse
	(*DeinitRequest)(nil),  // 2: spire.service.private.init.v1.DeinitRequest
	(*DeinitResponse)(nil), // 3: spire.service.private.init.v1.DeinitResponse
}
var file_spire_service_private_init_v1_init_proto_depIdxs = []int32{
	0, // 0: spire.service.private.init.v1.Init.Init:input_type -> spire.service.private.init.v1.InitRequest
	2, // 1: spire.service.private.init.v1.Init.Deinit:input_type -> spire.service.private.init.v1.DeinitRequest
	1, // 2: spire.service.private.init.v1.Init.Init:output_type -> spire.service.private.init.v1.InitResponse
	3, // 3: spire.service.private.init.v1.Init.Deinit:output_type -> spire.service.private.init.v1.DeinitResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spire_service_private_init_v1_init_proto_init() }
func file_spire_service_private_init_v1_init_proto_init() {
	if File_spire_service_private_init_v1_init_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_service_private_init_v1_init_proto_rawDesc), len(file_spire_service_private_init_v1_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_service_private_init_v1_init_proto_goTypes,
		DependencyIndexes: file_spire_service_private_init_v1_init_proto_depIdxs,
		MessageInfos:      file_spire_service_private_init_v1_init_proto_msgTypes,
	}.Build()
	File_spire_service_private_init_v1_init_proto = out.File
	file_spire_service_private_init_v1_init_proto_goTypes = nil
	file_spire_service_private_init_v1_init_proto_depIdxs = nil
}
