// Code generated by protoc-gen-go-spire. DO NOT EDIT.

package svitrustbundlesourcev1

import (
	pluginsdk "github.com/spiffe/spire-plugin-sdk/pluginsdk"
	grpc "google.golang.org/grpc"
)

func TrustBundleSourcePluginServer(server TrustBundleSourceServer) pluginsdk.PluginServer {
	return trustBundleSourcePluginServer{TrustBundleSourceServer: server}
}

type trustBundleSourcePluginServer struct {
	TrustBundleSourceServer
}

func (s trustBundleSourcePluginServer) Type() string {
	return "TrustBundleSource"
}

func (s trustBundleSourcePluginServer) GRPCServiceName() string {
	return "spire.plugin.agent.trustbundlesource.v1.TrustBundleSource"
}

func (s trustBundleSourcePluginServer) RegisterServer(server *grpc.Server) interface{} {
	RegisterTrustBundleSourceServer(server, s.TrustBundleSourceServer)
	return s.TrustBundleSourceServer
}

type TrustBundleSourcePluginClient struct {
	TrustBundleSourceClient
}

func (s TrustBundleSourcePluginClient) Type() string {
	return "TrustBundleSource"
}

func (c *TrustBundleSourcePluginClient) IsInitialized() bool {
	return c.TrustBundleSourceClient != nil
}

func (c *TrustBundleSourcePluginClient) GRPCServiceName() string {
	return "spire.plugin.agent.trustbundlesource.v1.TrustBundleSource"
}

func (c *TrustBundleSourcePluginClient) InitClient(conn grpc.ClientConnInterface) interface{} {
	c.TrustBundleSourceClient = NewTrustBundleSourceClient(conn)
	return c.TrustBundleSourceClient
}
