// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/hostservice/server/agentstore/v1/agentstore.proto

package agentstorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the agent to get information for.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoRequest) Reset() {
	*x = GetAgentInfoRequest{}
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoRequest) ProtoMessage() {}

func (x *GetAgentInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAgentInfoRequest) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescGZIP(), []int{0}
}

func (x *GetAgentInfoRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The agent information.
	Info          *AgentInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentInfoResponse) Reset() {
	*x = GetAgentInfoResponse{}
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentInfoResponse) ProtoMessage() {}

func (x *GetAgentInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAgentInfoResponse) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentInfoResponse) GetInfo() *AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type AgentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the agent.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_spire_hostservice_server_agentstore_v1_agentstore_proto protoreflect.FileDescriptor

const file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDesc = "" +
	"\n" +
	"7spire/hostservice/server/agentstore/v1/agentstore.proto\x12&spire.hostservice.server.agentstore.v1\"0\n" +
	"\x13GetAgentInfoRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"]\n" +
	"\x14GetAgentInfoResponse\x12E\n" +
	"\x04info\x18\x01 \x01(\v21.spire.hostservice.server.agentstore.v1.AgentInfoR\x04info\"&\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId2\x98\x01\n" +
	"\n" +
	"AgentStore\x12\x89\x01\n" +
	"\fGetAgentInfo\x12;.spire.hostservice.server.agentstore.v1.GetAgentInfoRequest\x1a<.spire.hostservice.server.agentstore.v1.GetAgentInfoResponseB^Z\\github.com/spiffe/spire-plugin-sdk/proto/spire/hostservice/server/agentstore/v1;agentstorev1b\x06proto3"

var (
	file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescOnce sync.Once
	file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescData []byte
)

func file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescGZIP() []byte {
	file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescOnce.Do(func() {
		file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDesc), len(file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDesc)))
	})
	return file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDescData
}

var file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spire_hostservice_server_agentstore_v1_agentstore_proto_goTypes = []any{
	(*GetAgentInfoRequest)(nil),  // 0: spire.hostservice.server.agentstore.v1.GetAgentInfoRequest
	(*GetAgentInfoResponse)(nil), // 1: spire.hostservice.server.agentstore.v1.GetAgentInfoResponse
	(*AgentInfo)(nil),            // 2: spire.hostservice.server.agentstore.v1.AgentInfo
}
var file_spire_hostservice_server_agentstore_v1_agentstore_proto_depIdxs = []int32{
	2, // 0: spire.hostservice.server.agentstore.v1.GetAgentInfoResponse.info:type_name -> spire.hostservice.server.agentstore.v1.AgentInfo
	0, // 1: spire.hostservice.server.agentstore.v1.AgentStore.GetAgentInfo:input_type -> spire.hostservice.server.agentstore.v1.GetAgentInfoRequest
	1, // 2: spire.hostservice.server.agentstore.v1.AgentStore.GetAgentInfo:output_type -> spire.hostservice.server.agentstore.v1.GetAgentInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_spire_hostservice_server_agentstore_v1_agentstore_proto_init() }
func file_spire_hostservice_server_agentstore_v1_agentstore_proto_init() {
	if File_spire_hostservice_server_agentstore_v1_agentstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDesc), len(file_spire_hostservice_server_agentstore_v1_agentstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_hostservice_server_agentstore_v1_agentstore_proto_goTypes,
		DependencyIndexes: file_spire_hostservice_server_agentstore_v1_agentstore_proto_depIdxs,
		MessageInfos:      file_spire_hostservice_server_agentstore_v1_agentstore_proto_msgTypes,
	}.Build()
	File_spire_hostservice_server_agentstore_v1_agentstore_proto = out.File
	file_spire_hostservice_server_agentstore_v1_agentstore_proto_goTypes = nil
	file_spire_hostservice_server_agentstore_v1_agentstore_proto_depIdxs = nil
}
