// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spire/plugin/agent/keymanager/v1/keymanager.proto

package keymanagerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_UNSPECIFIED_KEY_TYPE KeyType = 0
	KeyType_EC_P256              KeyType = 1
	KeyType_EC_P384              KeyType = 2
	KeyType_RSA_2048             KeyType = 3
	KeyType_RSA_4096             KeyType = 4
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "UNSPECIFIED_KEY_TYPE",
		1: "EC_P256",
		2: "EC_P384",
		3: "RSA_2048",
		4: "RSA_4096",
	}
	KeyType_value = map[string]int32{
		"UNSPECIFIED_KEY_TYPE": 0,
		"EC_P256":              1,
		"EC_P384":              2,
		"RSA_2048":             3,
		"RSA_4096":             4,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{0}
}

type HashAlgorithm int32

const (
	HashAlgorithm_UNSPECIFIED_HASH_ALGORITHM HashAlgorithm = 0
	// These entries (and their values) line up with a subset of the go
	// crypto.Hash constants.
	HashAlgorithm_SHA224     HashAlgorithm = 4
	HashAlgorithm_SHA256     HashAlgorithm = 5
	HashAlgorithm_SHA384     HashAlgorithm = 6
	HashAlgorithm_SHA512     HashAlgorithm = 7
	HashAlgorithm_SHA3_224   HashAlgorithm = 10
	HashAlgorithm_SHA3_256   HashAlgorithm = 11
	HashAlgorithm_SHA3_384   HashAlgorithm = 12
	HashAlgorithm_SHA3_512   HashAlgorithm = 13
	HashAlgorithm_SHA512_224 HashAlgorithm = 14
	HashAlgorithm_SHA512_256 HashAlgorithm = 15
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0:  "UNSPECIFIED_HASH_ALGORITHM",
		4:  "SHA224",
		5:  "SHA256",
		6:  "SHA384",
		7:  "SHA512",
		10: "SHA3_224",
		11: "SHA3_256",
		12: "SHA3_384",
		13: "SHA3_512",
		14: "SHA512_224",
		15: "SHA512_256",
	}
	HashAlgorithm_value = map[string]int32{
		"UNSPECIFIED_HASH_ALGORITHM": 0,
		"SHA224":                     4,
		"SHA256":                     5,
		"SHA384":                     6,
		"SHA512":                     7,
		"SHA3_224":                   10,
		"SHA3_256":                   11,
		"SHA3_384":                   12,
		"SHA3_512":                   13,
		"SHA512_224":                 14,
		"SHA512_256":                 15,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes[1].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes[1]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{1}
}

type PublicKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the key, as provided when the key was created.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required. The type of the key.
	Type KeyType `protobuf:"varint,2,opt,name=type,proto3,enum=spire.plugin.agent.keymanager.v1.KeyType" json:"type,omitempty"`
	// Required. The public key data (PKIX encoded).
	PkixData []byte `protobuf:"bytes,3,opt,name=pkix_data,json=pkixData,proto3" json:"pkix_data,omitempty"`
	// Required. Fingerprint of the public key. The (id,fingerprint) tuple
	// uniquely identifies an "instance" of the key. When a key is overwritten
	// the fingerprint changes, indicating a different "instance" of that key
	// under the given ID.
	//
	// Proper key rotation requires that SPIRE not overwrite a key while it is
	// actively being used to sign data so that if the rotation operation
	// fails, SPIRE still has a valid key to use. SPIRE compares the
	// fingerprint returned from signing operations with the fingerprint it
	// expected for the key as a way to detect when it has mismanaged keys.
	// This is a mitigating measure and not expected to fail under normal
	// circumstances.
	//
	// There is no requirement that plugins persist the fingerprint. It can be
	// newly generated as long as it remains consistent for a given "instance"
	// of the key during runtime.
	//
	// The fingerprinting algorithm is also left to plugin implementations. A
	// native implementation is a non-cryptographic hash over the PKIX data.
	Fingerprint   string `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicKey) GetType() KeyType {
	if x != nil {
		return x.Type
	}
	return KeyType_UNSPECIFIED_KEY_TYPE
}

func (x *PublicKey) GetPkixData() []byte {
	if x != nil {
		return x.PkixData
	}
	return nil
}

func (x *PublicKey) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type GenerateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID to give the generated key (or to identify the existing
	// key to overwrite (see GenerateKey).
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Required. The type of the key to generate.
	KeyType       KeyType `protobuf:"varint,2,opt,name=key_type,json=keyType,proto3,enum=spire.plugin.agent.keymanager.v1.KeyType" json:"key_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GenerateKeyRequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_UNSPECIFIED_KEY_TYPE
}

type GenerateKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The generated key.
	PublicKey     *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyResponse) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetPublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the key to retrieve.
	KeyId         string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetPublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The public key to return.
	PublicKey     *PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublicKeyResponse) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetPublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysRequest) Reset() {
	*x = GetPublicKeysRequest{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysRequest) ProtoMessage() {}

func (x *GetPublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{5}
}

type GetPublicKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The public keys managed by the KeyManager. May be empty.
	PublicKeys    []*PublicKey `protobuf:"bytes,1,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeysResponse) Reset() {
	*x = GetPublicKeysResponse{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeysResponse) ProtoMessage() {}

func (x *GetPublicKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeysResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeysResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{6}
}

func (x *GetPublicKeysResponse) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

type SignDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the key to use to sign the data.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Required. The data to sign.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Required. The signature options. The PSS options are only valid
	// for RSA keys.
	//
	// Types that are valid to be assigned to SignerOpts:
	//
	//	*SignDataRequest_HashAlgorithm
	//	*SignDataRequest_PssOptions
	SignerOpts    isSignDataRequest_SignerOpts `protobuf_oneof:"signer_opts"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDataRequest) Reset() {
	*x = SignDataRequest{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataRequest) ProtoMessage() {}

func (x *SignDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataRequest.ProtoReflect.Descriptor instead.
func (*SignDataRequest) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{7}
}

func (x *SignDataRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignDataRequest) GetSignerOpts() isSignDataRequest_SignerOpts {
	if x != nil {
		return x.SignerOpts
	}
	return nil
}

func (x *SignDataRequest) GetHashAlgorithm() HashAlgorithm {
	if x != nil {
		if x, ok := x.SignerOpts.(*SignDataRequest_HashAlgorithm); ok {
			return x.HashAlgorithm
		}
	}
	return HashAlgorithm_UNSPECIFIED_HASH_ALGORITHM
}

func (x *SignDataRequest) GetPssOptions() *SignDataRequest_PSSOptions {
	if x != nil {
		if x, ok := x.SignerOpts.(*SignDataRequest_PssOptions); ok {
			return x.PssOptions
		}
	}
	return nil
}

type isSignDataRequest_SignerOpts interface {
	isSignDataRequest_SignerOpts()
}

type SignDataRequest_HashAlgorithm struct {
	HashAlgorithm HashAlgorithm `protobuf:"varint,3,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=spire.plugin.agent.keymanager.v1.HashAlgorithm,oneof"`
}

type SignDataRequest_PssOptions struct {
	PssOptions *SignDataRequest_PSSOptions `protobuf:"bytes,4,opt,name=pss_options,json=pssOptions,proto3,oneof"`
}

func (*SignDataRequest_HashAlgorithm) isSignDataRequest_SignerOpts() {}

func (*SignDataRequest_PssOptions) isSignDataRequest_SignerOpts() {}

type SignDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The signature of the data.
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Required. The fingerprint of the key used to sign the data.
	KeyFingerprint string `protobuf:"bytes,2,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignDataResponse) Reset() {
	*x = SignDataResponse{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataResponse) ProtoMessage() {}

func (x *SignDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataResponse.ProtoReflect.Descriptor instead.
func (*SignDataResponse) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{8}
}

func (x *SignDataResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignDataResponse) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

type SignDataRequest_PSSOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The salt length.
	SaltLength int32 `protobuf:"varint,1,opt,name=salt_length,json=saltLength,proto3" json:"salt_length,omitempty"`
	// Required. The hash algorithm.
	HashAlgorithm HashAlgorithm `protobuf:"varint,2,opt,name=hash_algorithm,json=hashAlgorithm,proto3,enum=spire.plugin.agent.keymanager.v1.HashAlgorithm" json:"hash_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDataRequest_PSSOptions) Reset() {
	*x = SignDataRequest_PSSOptions{}
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataRequest_PSSOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataRequest_PSSOptions) ProtoMessage() {}

func (x *SignDataRequest_PSSOptions) ProtoReflect() protoreflect.Message {
	mi := &file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataRequest_PSSOptions.ProtoReflect.Descriptor instead.
func (*SignDataRequest_PSSOptions) Descriptor() ([]byte, []int) {
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP(), []int{7, 0}
}

func (x *SignDataRequest_PSSOptions) GetSaltLength() int32 {
	if x != nil {
		return x.SaltLength
	}
	return 0
}

func (x *SignDataRequest_PSSOptions) GetHashAlgorithm() HashAlgorithm {
	if x != nil {
		return x.HashAlgorithm
	}
	return HashAlgorithm_UNSPECIFIED_HASH_ALGORITHM
}

var File_spire_plugin_agent_keymanager_v1_keymanager_proto protoreflect.FileDescriptor

const file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDesc = "" +
	"\n" +
	"1spire/plugin/agent/keymanager/v1/keymanager.proto\x12 spire.plugin.agent.keymanager.v1\"\x99\x01\n" +
	"\tPublicKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\x04type\x18\x02 \x01(\x0e2).spire.plugin.agent.keymanager.v1.KeyTypeR\x04type\x12\x1b\n" +
	"\tpkix_data\x18\x03 \x01(\fR\bpkixData\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\"q\n" +
	"\x12GenerateKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12D\n" +
	"\bkey_type\x18\x02 \x01(\x0e2).spire.plugin.agent.keymanager.v1.KeyTypeR\akeyType\"a\n" +
	"\x13GenerateKeyResponse\x12J\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2+.spire.plugin.agent.keymanager.v1.PublicKeyR\tpublicKey\",\n" +
	"\x13GetPublicKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"b\n" +
	"\x14GetPublicKeyResponse\x12J\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2+.spire.plugin.agent.keymanager.v1.PublicKeyR\tpublicKey\"\x16\n" +
	"\x14GetPublicKeysRequest\"e\n" +
	"\x15GetPublicKeysResponse\x12L\n" +
	"\vpublic_keys\x18\x01 \x03(\v2+.spire.plugin.agent.keymanager.v1.PublicKeyR\n" +
	"publicKeys\"\x8e\x03\n" +
	"\x0fSignDataRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12X\n" +
	"\x0ehash_algorithm\x18\x03 \x01(\x0e2/.spire.plugin.agent.keymanager.v1.HashAlgorithmH\x00R\rhashAlgorithm\x12_\n" +
	"\vpss_options\x18\x04 \x01(\v2<.spire.plugin.agent.keymanager.v1.SignDataRequest.PSSOptionsH\x00R\n" +
	"pssOptions\x1a\x85\x01\n" +
	"\n" +
	"PSSOptions\x12\x1f\n" +
	"\vsalt_length\x18\x01 \x01(\x05R\n" +
	"saltLength\x12V\n" +
	"\x0ehash_algorithm\x18\x02 \x01(\x0e2/.spire.plugin.agent.keymanager.v1.HashAlgorithmR\rhashAlgorithmB\r\n" +
	"\vsigner_opts\"Y\n" +
	"\x10SignDataResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12'\n" +
	"\x0fkey_fingerprint\x18\x02 \x01(\tR\x0ekeyFingerprint*Y\n" +
	"\aKeyType\x12\x18\n" +
	"\x14UNSPECIFIED_KEY_TYPE\x10\x00\x12\v\n" +
	"\aEC_P256\x10\x01\x12\v\n" +
	"\aEC_P384\x10\x02\x12\f\n" +
	"\bRSA_2048\x10\x03\x12\f\n" +
	"\bRSA_4096\x10\x04*\xb7\x01\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aUNSPECIFIED_HASH_ALGORITHM\x10\x00\x12\n" +
	"\n" +
	"\x06SHA224\x10\x04\x12\n" +
	"\n" +
	"\x06SHA256\x10\x05\x12\n" +
	"\n" +
	"\x06SHA384\x10\x06\x12\n" +
	"\n" +
	"\x06SHA512\x10\a\x12\f\n" +
	"\bSHA3_224\x10\n" +
	"\x12\f\n" +
	"\bSHA3_256\x10\v\x12\f\n" +
	"\bSHA3_384\x10\f\x12\f\n" +
	"\bSHA3_512\x10\r\x12\x0e\n" +
	"\n" +
	"SHA512_224\x10\x0e\x12\x0e\n" +
	"\n" +
	"SHA512_256\x10\x0f2\xfd\x03\n" +
	"\n" +
	"KeyManager\x12z\n" +
	"\vGenerateKey\x124.spire.plugin.agent.keymanager.v1.GenerateKeyRequest\x1a5.spire.plugin.agent.keymanager.v1.GenerateKeyResponse\x12}\n" +
	"\fGetPublicKey\x125.spire.plugin.agent.keymanager.v1.GetPublicKeyRequest\x1a6.spire.plugin.agent.keymanager.v1.GetPublicKeyResponse\x12\x80\x01\n" +
	"\rGetPublicKeys\x126.spire.plugin.agent.keymanager.v1.GetPublicKeysRequest\x1a7.spire.plugin.agent.keymanager.v1.GetPublicKeysResponse\x12q\n" +
	"\bSignData\x121.spire.plugin.agent.keymanager.v1.SignDataRequest\x1a2.spire.plugin.agent.keymanager.v1.SignDataResponseBXZVgithub.com/spiffe/spire-plugin-sdk/proto/spire/plugin/agent/keymanager/v1;keymanagerv1b\x06proto3"

var (
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescOnce sync.Once
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescData []byte
)

func file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescGZIP() []byte {
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescOnce.Do(func() {
		file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDesc), len(file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDesc)))
	})
	return file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDescData
}

var file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_spire_plugin_agent_keymanager_v1_keymanager_proto_goTypes = []any{
	(KeyType)(0),                       // 0: spire.plugin.agent.keymanager.v1.KeyType
	(HashAlgorithm)(0),                 // 1: spire.plugin.agent.keymanager.v1.HashAlgorithm
	(*PublicKey)(nil),                  // 2: spire.plugin.agent.keymanager.v1.PublicKey
	(*GenerateKeyRequest)(nil),         // 3: spire.plugin.agent.keymanager.v1.GenerateKeyRequest
	(*GenerateKeyResponse)(nil),        // 4: spire.plugin.agent.keymanager.v1.GenerateKeyResponse
	(*GetPublicKeyRequest)(nil),        // 5: spire.plugin.agent.keymanager.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),       // 6: spire.plugin.agent.keymanager.v1.GetPublicKeyResponse
	(*GetPublicKeysRequest)(nil),       // 7: spire.plugin.agent.keymanager.v1.GetPublicKeysRequest
	(*GetPublicKeysResponse)(nil),      // 8: spire.plugin.agent.keymanager.v1.GetPublicKeysResponse
	(*SignDataRequest)(nil),            // 9: spire.plugin.agent.keymanager.v1.SignDataRequest
	(*SignDataResponse)(nil),           // 10: spire.plugin.agent.keymanager.v1.SignDataResponse
	(*SignDataRequest_PSSOptions)(nil), // 11: spire.plugin.agent.keymanager.v1.SignDataRequest.PSSOptions
}
var file_spire_plugin_agent_keymanager_v1_keymanager_proto_depIdxs = []int32{
	0,  // 0: spire.plugin.agent.keymanager.v1.PublicKey.type:type_name -> spire.plugin.agent.keymanager.v1.KeyType
	0,  // 1: spire.plugin.agent.keymanager.v1.GenerateKeyRequest.key_type:type_name -> spire.plugin.agent.keymanager.v1.KeyType
	2,  // 2: spire.plugin.agent.keymanager.v1.GenerateKeyResponse.public_key:type_name -> spire.plugin.agent.keymanager.v1.PublicKey
	2,  // 3: spire.plugin.agent.keymanager.v1.GetPublicKeyResponse.public_key:type_name -> spire.plugin.agent.keymanager.v1.PublicKey
	2,  // 4: spire.plugin.agent.keymanager.v1.GetPublicKeysResponse.public_keys:type_name -> spire.plugin.agent.keymanager.v1.PublicKey
	1,  // 5: spire.plugin.agent.keymanager.v1.SignDataRequest.hash_algorithm:type_name -> spire.plugin.agent.keymanager.v1.HashAlgorithm
	11, // 6: spire.plugin.agent.keymanager.v1.SignDataRequest.pss_options:type_name -> spire.plugin.agent.keymanager.v1.SignDataRequest.PSSOptions
	1,  // 7: spire.plugin.agent.keymanager.v1.SignDataRequest.PSSOptions.hash_algorithm:type_name -> spire.plugin.agent.keymanager.v1.HashAlgorithm
	3,  // 8: spire.plugin.agent.keymanager.v1.KeyManager.GenerateKey:input_type -> spire.plugin.agent.keymanager.v1.GenerateKeyRequest
	5,  // 9: spire.plugin.agent.keymanager.v1.KeyManager.GetPublicKey:input_type -> spire.plugin.agent.keymanager.v1.GetPublicKeyRequest
	7,  // 10: spire.plugin.agent.keymanager.v1.KeyManager.GetPublicKeys:input_type -> spire.plugin.agent.keymanager.v1.GetPublicKeysRequest
	9,  // 11: spire.plugin.agent.keymanager.v1.KeyManager.SignData:input_type -> spire.plugin.agent.keymanager.v1.SignDataRequest
	4,  // 12: spire.plugin.agent.keymanager.v1.KeyManager.GenerateKey:output_type -> spire.plugin.agent.keymanager.v1.GenerateKeyResponse
	6,  // 13: spire.plugin.agent.keymanager.v1.KeyManager.GetPublicKey:output_type -> spire.plugin.agent.keymanager.v1.GetPublicKeyResponse
	8,  // 14: spire.plugin.agent.keymanager.v1.KeyManager.GetPublicKeys:output_type -> spire.plugin.agent.keymanager.v1.GetPublicKeysResponse
	10, // 15: spire.plugin.agent.keymanager.v1.KeyManager.SignData:output_type -> spire.plugin.agent.keymanager.v1.SignDataResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_spire_plugin_agent_keymanager_v1_keymanager_proto_init() }
func file_spire_plugin_agent_keymanager_v1_keymanager_proto_init() {
	if File_spire_plugin_agent_keymanager_v1_keymanager_proto != nil {
		return
	}
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes[7].OneofWrappers = []any{
		(*SignDataRequest_HashAlgorithm)(nil),
		(*SignDataRequest_PssOptions)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDesc), len(file_spire_plugin_agent_keymanager_v1_keymanager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spire_plugin_agent_keymanager_v1_keymanager_proto_goTypes,
		DependencyIndexes: file_spire_plugin_agent_keymanager_v1_keymanager_proto_depIdxs,
		EnumInfos:         file_spire_plugin_agent_keymanager_v1_keymanager_proto_enumTypes,
		MessageInfos:      file_spire_plugin_agent_keymanager_v1_keymanager_proto_msgTypes,
	}.Build()
	File_spire_plugin_agent_keymanager_v1_keymanager_proto = out.File
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_goTypes = nil
	file_spire_plugin_agent_keymanager_v1_keymanager_proto_depIdxs = nil
}
